services:
  dinghy_layer:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_dynamic:/traefik/dynamic
    command: ["sh", "-c", "/usr/local/bin/dinghy-layer"]
    labels:
      - "traefik.enable=false"

  join_networks:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      ["sh", "-c", "/usr/local/bin/join-networks -container-name http-proxy"]
    labels:
      - "traefik.enable=false"

  dns:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - "19322:19322/udp"
    command: ["sh", "-c", "/usr/local/bin/dns-server"]
    labels:
      - "traefik.enable=false"

  traefik:
    build:
      context: ./build/traefik
      dockerfile: Dockerfile
    container_name: http-proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - traefik_dynamic:/traefik/dynamic
    labels:
      - "traefik.enable=false"

volumes:
  traefik_dynamic:
